### ISSUE TITLE
Path variables are not replaced

### ISSUE THREAD

**Issue by yramrax** [launchiamenterprise/keyrunner#1]
I've used the VSCode extions v1.0.28

Steps to reproduce:
Import the simple test collection: [Test.json](https://github.com/launchiamenterprise/keyrunner/files/14377640/Test.json)
when sending the request the path variable will not be replaced.

I've looked in the  UrlBuilder.js and it seems that the baseURI with the replaced values is then never used and so the original url doesn't change

**Comment by launchiamenterprise** [comment]
@yramrax Released v1.0.29 with the fix. Again thanks for reporting the issue

**Comment by yramrax** [comment]
Thank you very much for the fast fix, I've tried it with the new version and it is working perfectly
