### ISSUE TITLE
Add description to parameters

### ISSUE THREAD

**Issue by noyb2x** [launchiamenterprise/keyrunner#15]
As requested in a mail reply to me I create this issue.

Great tool, but it would be nice the user can add descriptions to parameters.
eg I now have 1 parameter for an api, but multiple guids as value.
Now I always need to lookup what (who) the guid is before I can enable that specific one and send to the api.

So adding a description to the key/value would save a lot of lookup time elsewhere.

Maybe even in other parts of the options a description would be nice, like body content...

**Comment by launchiamenterprise** [comment]
This feature has been added now with v1.0.44 . Please update the app

**Comment by noyb2x** [comment]
Super, thanks to everybody in the team!
