### ISSUE TITLE
Unable to run GET requests from playground when request is dependent on one of JSON object part of JSON Array from previous API response

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#17]
When we try to perform chaining of requests using “playground” option we are unable to tag query/path params of GET API request to JSON object which is part of JSON Array from previous API response in request flow. Below are detailed steps for the same.

I am using Key Runner Windows/Desktop Application - v1.0.45.0

1.	I have created a “Request Flow” with 5 requests which is needed as a part of chaining of requests as shown below in screen shot: 
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/e54afaff-b04c-4059-a7b2-877e2871435a)

a.	One of GET API request need path param value from previous API call as depicted below.
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/0b66acdc-daa3-44d7-826e-2f964c0bc2e0)

b.	The Previous API call has API response in JSON Array format, and we need a particular value from JSON array to be used as path param in next API call (which is failed in above screen shot) and we have mapped field against path param as shown in below screenshot.

The below screen shot shows -- Previous API call response: 
![1](https://github.com/launchiamenterprise/keyrunner/assets/168065372/2f083ed8-5c6a-473b-b4bb-8c8b052905d0)

The below screen shot shows -- Value Mapping to Path Param in next API call: 
![2](https://github.com/launchiamenterprise/keyrunner/assets/168065372/2269183f-6053-4728-a7fb-1e5c1011dc36)

Further when we try to run requests in request flow via playground option, later API request (APIRequest-Get4) fails as it didn’t fetched value from previous API response (APIRequest-Get1) to mapped path parameters. So how this scenario can be achieved.

**Comment by akhot09** [comment]
Hi @launchiamenterprise -- Thanks for reply!
Solution provided is working for example depicted in screen shots.

**Comment by launchiamenterprise** [comment]
perfect , closing the issue for now. we will update the documentation
