### ISSUE TITLE
No checkbox option available for POST requests of RAW Type in playground option, when request is dependent on one of JSON object part of JSON Array from previous API response

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#18]
When we try to perform chaining of requests using “playground” option we are unable to tag JSON API request params (sent with RAW Type) part of POST API request to JSON object / JSON parameter from previous API response in request flow. Below are detailed steps for the same.

I am using Key Runner Windows/Desktop Application - v1.0.45.0

1. I have created a “Request Flow” with 5 requests which is needed as a part of chaining of requests as shown below in screen shot: 
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/b42f3efa-287c-4628-b545-864a4069523e)

a.	The POST request API call (of RAW type) need values from all previous GET API calls (as shown in above screenshot). 
b.	The Previous API calls have API response in JSON Array format, and we need a particular value from JSON array to be used as request body param in next POST API call (which is failed in above screen shot).
The below screen shot shows -- Previous API call responses: 
![1](https://github.com/launchiamenterprise/keyrunner/assets/168065372/645eedab-1ca3-4a11-a83a-a01fb63eccc6)

![2](https://github.com/launchiamenterprise/keyrunner/assets/168065372/b5879dd3-e76f-43c1-943f-c7f231f84b78)

In below screen shot we can see that -- to map values from previous GET API responses, we don’t see any checkbox option available to map JSON request parameters (part of POST request body) to JSON object from previous GET API call responses.

![3](https://github.com/launchiamenterprise/keyrunner/assets/168065372/c974432f-f98f-4bf7-a804-d081ebff3d70)

Further when we try to run requests in request flow via playground option, later POST API request (APIRequest-Post1) fails as it didn’t fetched value from previous API response (Ex: APIRequest-Get1, APIRequest-Get2, APIRequest-Get3) as we don’t see any checkboxes to map value from previous API call responses. So how this scenario can be achieved.

**Comment by launchiamenterprise** [comment]
we completed the development of this feature and are in testing phase, we will release a minor version shortly tonight or tomorrow.

**Comment by launchiamenterprise** [comment]
@akhot09 this has been introduced with V1.0.47

**Comment by akhot09** [comment]
@launchiamenterprise - Can you please help/guide us with relevant documentation/ docs resource link which we can follow so that we can use this new feature. 

I am using KeyRunner v1.0.50 version as a extension in VS code and dont see any check boxes against JSON object part of Request Body added of type - RAW part of POST method. Please find below screen shot : 
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/24f317ff-bbc6-49eb-9271-cd5697320b96)

**Comment by launchiamenterprise** [comment]
@akhot09  please see the below documentation and if you are still running into issues, let us know 

https://docs.keyrunner.app/docs/Flows.html
