### ISSUE TITLE
No feature/provision to write “Pre-Request” Script/ “Post-Request” Scripts

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#19]
If we need send any request to API call (like calling Key Vault APIs) before running required API call, we don’t see any “Pre-Request Script” tab (Like in Postman) in Key Runner API client. Also is there any plan to provide “Post-Request” Script tab, so that we can capture needed values from API response or perform validations using custom code.

I am using Key Runner Windows/Desktop Application - v1.0.45.0

The current “Tests” tab provides limited option to perform API response validations with pre-defined set of assertions but does not provide any option to write any custom code/use of JSON path etc.

![4](https://github.com/launchiamenterprise/keyrunner/assets/168065372/144bf486-35bb-4c54-b027-c758b3e944b4)

**Comment by launchiamenterprise** [comment]
we are working on scripting feature(pre & post) and it will be released as part of next release. Regarding vault integrations we are building connectors for free version with which you can seamlessly integrate with vault to store or retrieve environment variables. We will update this thread once we release a new version.

**Comment by launchiamenterprise** [comment]
@akhot09  Beta version has been released for scripting with V#1.0.47 .

**Comment by akhot09** [comment]
@launchiamenterprise  -- 

Can you please point us to docs/documentation which brief us with commands, syntax to be used to add scripts in "Pre-Script" and "Post-Script" Scripts section which can help to perform post validations or capture values during chaining of requests.

Below screen shot is from v1.0.50 KeyRunner plugin installed part of Visual Studio Code : 
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/e27d8850-7cbc-4ffd-bc60-4ba3c301cb84)

**Comment by launchiamenterprise** [comment]
We are in the process of updating documentation and will update this thread once we document the usage. Hopefully by end of this week.

**Comment by launchiamenterprise** [comment]
please see the below documentation and let us know if you are running into any issues. This is still beta and we will improvise the functionality & features of scripting

https://docs.keyrunner.app/docs/scripting.html
