### ISSUE TITLE
Export collection to another API client format

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#20]
We don’t see any option to export Key Runner collection to other API client (Like Export as Postman Collection etc..). Checking/Looking for this option - as we can import postman collection in Key Runner API client using below highlighted option. 

I am using Key Runner Windows/Desktop Application - v1.0.45.0

![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/71b32ee3-5220-4a28-b6cc-13d709175f43)

As we can import any existing postman collection using below option in Key runner:

![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/d33456b7-a6fc-4e5c-be73-9d7725e10159)

**Comment by launchiamenterprise** [comment]
There is a bulk export option right above the collections 
<img width="187" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/4e5b8598-4dc2-45f2-974a-4c932a6ad976">
<img width="187" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/4e5b8598-4dc2-45f2-974a-4c932a6ad976">
<img width="187" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/4e5b8598-4dc2-45f2-974a-4c932a6ad976">


<img width="173" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/626416e3-7bd6-454f-a402-7d33efdbfe5b">
<img width="173" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/626416e3-7bd6-454f-a402-7d33efdbfe5b">
<img width="173" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/626416e3-7bd6-454f-a402-7d33efdbfe5b">

**Comment by akhot09** [comment]
@launchiamenterprise - Thanks for Update!

We have gone through Bulk Export option as well. But actually, as a part of this issue, we are looking forward for Option while exporting Key runner collection something like -- "Export as Postman Collection" or Export key runner collection in Postman Collection format (API client other than Key runner) as Key runner API client accepts "Postman" collection during import but same we don't while export option.

**Comment by launchiamenterprise** [comment]
can you try importing the exported keyrunner collection to postman ? It should do it as we made a common export with open API specification.

**Comment by launchiamenterprise** [comment]
got it , we will add this capability in the next release. Reopening this issue for tracking

**Comment by launchiamenterprise** [comment]
@akhot09 This feature has been introduced with V1.0.47

**Comment by akhot09** [comment]
@launchiamenterprise - Can you please point us to docs/documentation which brief us with steps to "Export Collection as Postman Collection". 

I am using KeyRunner extension version - v1.0.50 to Visual Studio Code and don't see any option which says - "Export as Postman Collection". Please find below screen shot for the same. 
![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/24695591-deb3-46a0-ac64-0fdc497ff51b)

**Comment by launchiamenterprise** [comment]
@akhot09  To ensure compatibility across various API clients including postman, we added this feature to export as open API format instead of keyrunner format or postman format. Please try importing the exported collection to postman or any other API clients and it should import without issues. Please let us know if you find any issue.
