### ISSUE TITLE
No export option for environment variables 

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#21]
I am using Key Runner Windows/Desktop Application - v1.0.45.0

We don’t see any option to export environment variables whereas on contrary we can see option to import environment variables. Please find below screenshots 

![5](https://github.com/launchiamenterprise/keyrunner/assets/168065372/99b38460-6a6c-4edc-88fe-40188950157f)

Whereas we can import environment variables using below option – 

![image](https://github.com/launchiamenterprise/keyrunner/assets/168065372/d9ffc07b-cfd0-4fdb-839b-90d30af1647b)

**Comment by launchiamenterprise** [comment]
This has been introduced with v1.0.50 . Please update the app
