### ISSUE TITLE
CLI Option to run exported Key Runner collection is not available

### ISSUE THREAD

**Issue by akhot09** [launchiamenterprise/keyrunner#22]
I have gone through Key Runner Docs website link (as given below), but we didn’t find any information related to running collection using CLI option. 
Do we have this option in Key Runner wherein we can run Key Runner collection using CLI option. If it’s available, please provide docs link for the same.

https://docs.keyrunner.app/docs/

**Comment by launchiamenterprise** [comment]
we are actively working on CLI at this time for free version. But for enterprise version we are exposing keyrunner API's which can be leveraged to integrate  with CI/CD pipelines.

**Comment by launchiamenterprise** [comment]
@akhot09 we’ve published our CLI! You can check it out and find all the details with below links.

https://www.npmjs.com/package/keyrunner?activeTab=readme

https://docs.keyrunner.app/docs/CLI.html
