### ISSUE TITLE
UI Issue: Not able to expand Request Body area vertically

### ISSUE THREAD

**Issue by billycrowson** [launchiamenterprise/keyrunner#23]
Using version 1.0.42

When inputting data into the Request body if it is longer than 16 lines the request is cut off, you can scroll down to the the other lines, but there is no way to expand this area into the free space.

![image](https://github.com/launchiamenterprise/keyrunner/assets/28060571/c7f414ab-cbf7-4b85-abef-baaa17234d15)
![image](https://github.com/launchiamenterprise/keyrunner/assets/28060571/84528825-93ec-4ea7-817c-9e6fffb601b4)

**Comment by launchiamenterprise** [comment]
@billycrowson  can you please update the app to v.1.0.47 . Please let us know if you still see the same behavior

<img width="718" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/f4c9e322-3fdc-4707-8559-faea86979914">

**Comment by billycrowson** [comment]
@launchiamenterprise I updated the app to v.1.0.47, but am still experiencing the behavior.

Screen recording:
https://github.com/launchiamenterprise/keyrunner/assets/28060571/fb7f1e88-99cf-4dce-8a0a-f5b42724843e

**Comment by launchiamenterprise** [comment]
We will address this CSS issue and incorporate the changes in the next minor version release

**Comment by launchiamenterprise** [comment]
@billycrowson this bug is addressed with  v1.0.60 . Please update to current version.
