### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by sw270** [launchiamenterprise/keyrunner#29]
Add ability to toggle Dark Mode off - some of the colors make it very difficult to read the results in the console and some people have a difficult time reading in Dark Mode.

**Comment by launchiamenterprise** [comment]
we are working on theming feature, Will update this thread once we publish the changes.

**Comment by launchiamenterprise** [comment]
@sw270 theming feature  has been introduced with v1.0.60 . Please update to current version

**Comment by sw270** [comment]
Great theming feature added!  Thank you!
