### ISSUE TITLE
Minor UI issues

### ISSUE THREAD

**Issue by yramrax** [launchiamenterprise/keyrunner#3]
I'm using the VSCode extension v1.0.29.

It seems that the main panels are behind the status bar and therefore you cannot scroll entirely to the bottom:
![image](https://github.com/launchiamenterprise/keyrunner/assets/160919975/465fd199-e949-480e-8278-bfc67f25142c)

There is no scrollbar vor the Environments making it impossible to see/change values if you have a lot of them:
![image](https://github.com/launchiamenterprise/keyrunner/assets/160919975/7187ac9f-d156-453e-8645-e24aa876fd22)

**Comment by launchiamenterprise** [comment]
Issue is now fixed with v1.0.30

**Comment by yramrax** [comment]
Thank you very much I can confirm that it works
