### ISSUE TITLE
Documentation request: Git integration to Azure DevOps repo

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#30]
User is struggling with git integration to an Azure DevOps repo and looking for documentation to assist

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management here is the documentation for Git integration .If the user is still experiencing issues with the integration, please let us know and we will take a look at it.

https://docs.keyrunner.app/docs/gitIntegration.html
