### ISSUE TITLE
Post Request submission - workspace goes blank

### ISSUE THREAD

**Issue by sw270** [launchiamenterprise/keyrunner#31]
Multiple team members are seeing this behavior.  We hit the submit on a post request and the KeyRunner workspace goes blank.  We only see the top menu.  The only way to resolve is to exit the application and re-launch it.  If the post request is re-submitted the same behavior happens, however, after a period of time the behavior goes away and we can submit the post request to obtain a new key for our get request.  V1.0.53
![snap217](https://github.com/user-attachments/assets/8f095bd4-f7a7-41fa-94bd-d4eb72b95081)

**Comment by launchiamenterprise** [comment]
Could you please provide a sample request that will help us reproduce this issue?

**Comment by sw270** [comment]
Would you like just the post request or the collection?

**Comment by launchiamenterprise** [comment]
@sw270 We've identified and addressed several issues with the request/response headers causing runtime errors. Most edge cases have been covered and fixed now. Please update to v1.0.56 and let us know if this resolved workspace going blank issue.

**Comment by sw270** [comment]
@launchiamenterprise V1.0.56 does resolve the workspace going blank issue.  Myself and a colleague have verified resolution.  Thank you very much for the very quick response.

**Comment by launchiamenterprise** [comment]
@sw270 thanks for confirming , Closing this issue !
