### ISSUE TITLE
text/xml Content-Type POST requests pass a Content-Length of 0

### ISSUE THREAD

**Issue by hex2bit** [launchiamenterprise/keyrunner#32]
When making a request that POSTs XML content, using the "text/xml" Content-Type, the Content-Length is passed as 0.  When trying another Content-Type like "application/xml", the content length is set to the appropriate value.

A quick test would be to use Postman's echo API:
https://postman-echo.com/post

Post some XML body content and set a Content-Type header with the value of text/xml.  Example result:
![image](https://github.com/user-attachments/assets/48649c0e-8e0a-417c-b173-a055a4eb9ae6)

With the content type set to application/xml:
![image](https://github.com/user-attachments/assets/1c98e1b9-96e7-4bf7-897e-d4ec60598c38)

**Comment by launchiamenterprise** [comment]
@hex2bit We've resolved the issue where text/xml Content-Type POST requests were passing a Content-Length of 0. This fix is included in the latest release, v1.0.57.

Please update to latest version and let us know if you are running into any issues.
