### ISSUE TITLE
Client Certificate to be used for MTLS Authentication on API Calls?

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#34]
Is it possible to register a client certificate to be used for MTLS authentication on API calls? Is this possible today or on the future roadmap?

**Comment by launchiamenterprise** [comment]
This feature is currently under development and is a priority on our roadmap. We're planning to include it in the next release. Will update this thread once it is released.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management With the release of v1.0.57, we have introduced mTLS certificate-based authentication. You can now register and use client certificates for MTLS authentication on API calls.

Here is the documentation : https://docs.keyrunner.app/docs/mtls.html

Let us know if you run into any issues with this feature
