### ISSUE TITLE
Exporting response from a collection

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#38]
Is there a way to export the response from a collection? I see there is an option to copy to clipboard from each separate call within the collection but not as a whole.
![Collection export](https://github.com/user-attachments/assets/eea07b9b-2e9d-4570-8a86-105ef90172b1)

**Comment by Mayo-API-Management** [comment]
Is there a current ETA for this enhancement? Thanks.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management We’ve completed development of this feature and are currently in the testing phase. It’s scheduled for release on August 5th.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management Export responses feature has been introduced with v1.0.60 . Please update to current version
