### ISSUE TITLE
Requests in the Playground are changed if you save them after running

### ISSUE THREAD

**Issue by yramrax** [launchiamenterprise/keyrunner#4]
I'm using the VSCode plugin v1.0.29

I've created a Request Flow with only one Request:
![image](https://github.com/launchiamenterprise/keyrunner/assets/160919975/d35a66d2-7347-4a27-9730-b111ef98bcfa)

When I run it, the Requests are updated with the changed values. Therefore it is not possible to simply change the environment and execute the Flow again directly. While this is not optimal the real issue is when the Request Flow is saved after being executed since the original is lost and the modified persisted. This is a screenshot after running, saving the flow, closing and reopening it:
![image](https://github.com/launchiamenterprise/keyrunner/assets/160919975/1ce190ff-6be1-43a3-8cfd-98bb0d362e66)

**Comment by launchiamenterprise** [comment]
Issue is now fixed with v1.0.30

**Comment by yramrax** [comment]
Thank you very much I can confirm that it works
