### ISSUE TITLE
Importing json collection results in out of order run of sub collections

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#41]
Importing collection that was originally setup in an order to run in a specific sequence of sub collections is now out of order and it appears the only way to fix this is it to update in the playground/ flow and save it. 
Perhaps a bug or feature request to have collections/ sub collections imported keep its chronological order?
![Collection out of order](https://github.com/user-attachments/assets/7c869c50-81cf-44b5-9c3f-e3134f1fedbd)

**Comment by Mayo-API-Management** [comment]
Is there a current ETA for this enhancement? Thanks.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management We’re developing a new feature to add this capability, with a tentative release date of 8/19.

**Comment by Mayo-API-Management** [comment]
Customer tested on 9/4, v1.0.62, and still an issue.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management  We're actively working on this and will have it ready for release on 9/9

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management  The issue has been resolved. Please update to V1.0.63
