### ISSUE TITLE
Inquiry: Time out on requests

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#42]
Is there a time out on requests?
e.g. If we run a collection and one call is "broken", how long will it take to skip that call and continue to the next call of the collection?

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management The default timeout for requests is set to 30 seconds. We're  introducing a new feature that will allow you to set custom timeouts both globally and at the individual request level. This feature will be live over the weekend.

https://github.com/launchiamenterprise/keyrunner/issues/40

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management request time-out feature has been introduced with v1.0.60 . Please update to latest
