### ISSUE TITLE
Suggestion to not replace localhost with 127.0.0.1

### ISSUE THREAD

**Issue by hex2bit** [launchiamenterprise/keyrunner#43]
**Is your feature request related to a problem? Please describe.**
The main problem with replacing "localhost" with 127.0.0.1 is with local web servers, especially when configured with a cert for HTTPS.  The certificate would be configured against the localhost domain and not 127.0.0.1 IP address.  Additionally, when developing .NET, IIS Express doesn't by default get configured to work with 127.0.01 and will throw a bad request error.

**Describe the solution you'd like**
I would like domains entered into the app to be used as entered, most specifically localhost.  In its current state, KeyRunner seems to translate localhost to 127.0.0.1 when making requests and it is causing problems for some use cases.

**Describe alternatives you've considered**
I don't really have an alternative other than using the curl script and modifying the domain to be localhost, or finding way to deal with local development servers to try and work around the issue.

**Additional context**
Example of it changing the domain, happens in the actual requests and the script snippets that get generated.
![image](https://github.com/user-attachments/assets/6d77e707-9921-4fd2-982d-d63cb93826d2)

Example response from IIS Express when run from KeyRunner using localhost that gets translated to 127.0.0.1:
![image](https://github.com/user-attachments/assets/ba7b15ed-bdc0-4aef-a325-a26ff490e497)

It does look like KeyRunner will ignore cert issues we calling 127.0.0.1, but you'll see validation messages like below when trying to run the generated scripts.  In my case, I have a local trusted cert setup for localhost to use in development/testing, but it would only apply if localhost is used as the domain in the request.

> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.

**Comment by launchiamenterprise** [comment]
@hex2bit  The issue has been resolved. Please update to V1.0.63 and let us know if you continue to experience any problems with replacing localhost with the IP address.

**Comment by hex2bit** [comment]
I'm seeing this behavior (replacing localhost with 127.0.0.1) happening in version 1.0.64 of the app.

**Comment by launchiamenterprise** [comment]
@hex2bit can you please update to latest and try (V1.0.65)?

**Comment by hex2bit** [comment]
This looks to be fixed in 1.0.65, thanks!
