### ISSUE TITLE
When entering or deleting characters from input fields, the cursor is placed at the end of the string

### ISSUE THREAD

**Issue by hex2bit** [launchiamenterprise/keyrunner#44]
**Describe the bug**
Whenever you type a character or delete a character from an input field, such as headers, body, params, etc... the cursor position is placed at the end of the string.  This makes it difficult to edit fields and I typically have to just clear and retype what I want in the field as that's easier to deal with.

**To Reproduce**
1. Place text in field
2. Try to edit something in the middle of the string

**Expected behavior**
I would expect the cursor to stay at the spot I'm editing and to not jump to the end of the string.

**Screenshots**
I don't have  screenshot, but I can try and capture something if needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version: 1.0.59

**Comment by launchiamenterprise** [comment]
Hi @hex2bit this issue is fixed, please update to latest version
