### ISSUE TITLE
KeyRunner issue to report: OAuth redirect not accepted by identity provider

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#45]
Is there any ability to edit the redirect/call uri sent by keyrunner (keyrunner://). We've run into some identity providers that seem to require an http:// or https:// address and will not allow keyrunner:// to be entered as a valid redirect uri on the app.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management  To launch the  app  from a web interaction we need to use a custom protocol like keyrunner://. This  serves as a unique identifier for the app and this is a standard approach for desktop applications. We’ll conduct some analysis and explore alternative solutions like using a localhost approach to handle the redirect. We’ll provide you with a detailed solution soon.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management  OAuth redirect is now supported via the following endpoint: https://api.keyrunner.app/v1/oauthRedirect .

Please update to latest (V#1.0.69)
