### ISSUE TITLE
Add support for global variables

### ISSUE THREAD

**Issue by zachdev** [launchiamenterprise/keyrunner#46]
We have variables/secrets that are shared across collections and environments. As of now, we are needing to duplicate these values in many places.

It would be great to have the functionality to define "global" variables that are accessible from any collection/environment - similar to Postman - to avoid duplications of secrets/variables.

**Comment by launchiamenterprise** [comment]
@zachdev Currently, environment variables are global and can be accessed across all collections. We're also working on adding support for collection level variables as outlined in this issue -https://github.com/launchiamenterprise/keyrunner/issues/48 . Could you clarify if your request is about needing global variables beyond what’s already available?  This will help us understand if its a duplicate or a different request.

**Comment by launchiamenterprise** [comment]
Issue is addressed with https://github.com/launchiamenterprise/keyrunner/issues/48
