### ISSUE TITLE
Add support for hotkeys

### ISSUE THREAD

**Issue by zachdev** [launchiamenterprise/keyrunner#47]
It would be great to have support for hotkeys - e.g. hitting "CTRL + S" to save a collection or environment after editing, rather than needing to click "Save".

**Comment by launchiamenterprise** [comment]
@zachdev This functionality is available in requests screen but there is a bug where it only works if you click outside the input text area first. We're aware of the issue and will fix it soon. We will also add the functionality for all the other screens where there is save button. Thanks for bringing this up

**Comment by launchiamenterprise** [comment]
@zachdev Please update to latest version (V1.0.64)
