### ISSUE TITLE
KeyRunner issue to report: Selecting Check for updates option disables all menu options

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#50]
**Describe the bug**
From the top menu, if you select the "Check for updates" options, no menu selections can be made after that.  The only recovery is to exit by using the X in the upper right corner and open the application again.

**To Reproduce**
1. Open KeyRunner
2. Click on Check for updates from the KeyRunner top menu.  Observe that a popup occurs with a title of "No Updates" and text of "Current version is up-to-date".
3. Press OK to exit the popup.
4. Try any other option in top menu, and nothing will execute.

**Expected behavior**
The menu items after checking for updates should not be disabled.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Version 22H2

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management we have this in our list of items for V#1.0.67. We will keep you posted once it is fixed and released.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management This has been address with our latest release (V#1.0.69), Please update to latest version.
