### ISSUE TITLE
Environment variables no longer working

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#54]
**Describe the bug**
Environment variables failing in API call. Variables turn red when viewing and call fails.

**To Reproduce**
Setup environment variables
make call using variables

**Expected behavior**
This was working on a version before 1.0.64

**Screenshots**
If applicable, add screenshots to help explain your problem......attaching
![global variables error](https://github.com/user-attachments/assets/1f206cfd-90ff-4cb6-acd2-7ad2b54e3701)

**Desktop (please complete the following information):**
 - OS: Windows - Version 1.0.64

**Additional context**

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management We're investigating this issue and will release a hotfix tonight. In the meantime, please roll back to (V1.0.63)  https://keyrunner.s3.us-west-2.amazonaws.com/keyrunner_1.0.63_x64_win.exe

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management did you select Environment on the top? We are not able to reproduce this issue in V1.0.64 .

<img width="830" alt="image" src="https://github.com/user-attachments/assets/1045cf97-5fff-46e6-8dbb-fefa0ce0ac28">

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management we were able to reproduce the issue and fixed it. Will release a minor version soon

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management can you please update to latest and try (V1.0.65)?
