### ISSUE TITLE
Import/Export collection buttons are hard to read when using VS Code extension light theme

### ISSUE THREAD

**Issue by suttonb** [launchiamenterprise/keyrunner#58]
**Describe the bug**

**To Reproduce**
1. Set VS Code color theme to any light theme
2. Go to Collections tab
3. Click on the + button below Search Collections

**Expected behavior**
The import/export buttons have a light icon on a dark background similar to the desktop app

**Screenshots**
![image](https://github.com/user-attachments/assets/93fbec57-2f3c-437d-bd97-e2c3d3bd9c44)

![image](https://github.com/user-attachments/assets/8b5217a7-a2c2-40c3-9693-f167afbdd6ce)

**VScode extension (please complete the following information):**
 - OS: Windows 11
 - VS Code Version: 1.93.1
 - KeyRunner extension version: v1.0.64

**Additional context**

**Comment by launchiamenterprise** [comment]
@suttonb This is fixed now. Please update to latest (V#1.0.67)
