### ISSUE TITLE
Unable to get time range Param to work

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#59]
**Describe the bug**
Is there a correct way to input time range in parameters?
Curl from a cmd window works as expected
curl -X GET "https://api.enterprise.apigee.com/v1/organizations/{org}/environments/{env}/stats/apiproxy?select=sum(message_count)&timeRange=09/20/2024%2000:00~09/27/2024%2000:00&timeUnit=month" -H "Authorization: Bearer {token}"

**To Reproduce**
I've tried slashes and hyphens for dates and no luck

**Expected behavior**
able to input time range in call

**Screenshots**
error message:
{"code":"analytics.dataapi.service.InvalidTimeRange","message":"Invalid timeRange - Invalid time 2024-09-01","contexts":[]}

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.0.63

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management can you please try with this URL without encoding time parameter: https://api.enterprise.apigee.com/v1/organizations/{org}/environments/{env}/stats/apiproxy?select=sum(message_count)&timeRange=09/20/2024 00:00~09/27/2024 00:00&timeUnit=month

**Comment by Mayo-API-Management** [comment]
Yes, that worked.

Thank you!

From: keyrunner ***@***.***>
Sent: Wednesday, October 2, 2024 12:21 PM
To: launchiamenterprise/keyrunner ***@***.***>
Cc: DL MCCP Apigee Admins ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [launchiamenterprise/keyrunner] Unable to get time range Param to work (Issue #59)


@Mayo-API-Management<https://github.com/Mayo-API-Management> can you please try with this URL without encoding time parameter: https://api.enterprise.apigee.com/v1/organizations/{org}/environments/{env}/stats/apiproxy?select=sum(message_count)&timeRange=09/20/2024<https://api.enterprise.apigee.com/v1/organizations/%7Borg%7D/environments/%7Benv%7D/stats/apiproxy?select=sum(message_count)&timeRange=09/20/2024> 00:00~09/27/2024 00:00&timeUnit=month

-
