### ISSUE TITLE
[Feature request] Add support for Websockets

### ISSUE THREAD

**Issue by Sharaf5** [launchiamenterprise/keyrunner#6]
Inspired by what thunder client implemented recently like in this screen

![Screenshot_20240305_211228](https://github.com/launchiamenterprise/keyrunner/assets/36330265/20465dde-3fc5-40f2-9507-e306d6a870d7)

This would extent the funtionality of your extention
also it may be useful for this feature request https://github.com/launchiamenterprise/keyrunner/issues/5

**Comment by launchiamenterprise** [comment]
Thank you for the suggestion and for using Keyrunner. Development work to support websocket and socket.io has been completed and will be released with the next version(V#1.0.31) probably by end of this week to the public.

<img width="908" alt="image" src="https://github.com/launchiamenterprise/keyrunner/assets/138955978/b49b9d17-cfea-48d4-8a25-71cfa90c64ad">

**Comment by Sharaf5** [comment]
Woow!
that's a very fast issue rosolution
I look forword to test websockets in the client itself
