### ISSUE TITLE
KeyRunner removing environment variables and then creating thousands of lines of blank variables. 

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#60]
**Describe the bug**
KeyRunner removing environment variables and then creating thousands of lines of blank variables. This freezes (not responding) KeyRunner until you are able to delete the environment. 3,000 plus lines of variables get created numbering 0 - ~3,000

**To Reproduce**
Not sure of exact steps but I only had one environment setup with 3 variables and this is the second time this has happened.

**Expected behavior**
Environment/ variables dont get wiped and numbered variable lines not created 

**Screenshots**
![Empty Environment lines](https://github.com/user-attachments/assets/67cdeaf3-8551-4f11-be4a-cef93264402e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.0.65

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management Does this happen only with imported environment variables or also with manually created ones?
Could you let us know if there were any specific actions performed just before the issue occurred (e.g., importing a environment file, modifying a variable)?

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management we are looking into this .Just to clarify, are you running any requests with pre or post-scripts that might be wiping out the environment variables ?

**Comment by Mayo-API-Management** [comment]
Yes, I was working on some pre-scripts as well during this. Sorry forgot to mention that.

Thanks!

From: keyrunner ***@***.***>
Sent: Wednesday, October 2, 2024 11:46 AM
To: launchiamenterprise/keyrunner ***@***.***>
Cc: DL MCCP Apigee Admins ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [launchiamenterprise/keyrunner] KeyRunner removing environment variables and then creating thousands of lines of blank variables. (Issue #60)


@Mayo-API-Management<https://github.com/Mayo-API-Management> we are looking into this .Just to clarify, are you running any requests with pre or post-scripts that might be wiping out the environment variables ?

-

**Comment by launchiamenterprise** [comment]
Thank you for the update! Could you please provide more details on whether the script creates or modifies environment variables? Does it include any loops? If possible, it would be helpful if you could email the script (with any sensitive data removed) to contact@keyrunner.app. We believe the issue might be related to the script, and reviewing it would help us investigate further.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management  just wanted to check in - is this still an issue?

**Comment by Mayo-API-Management** [comment]
This issue can be closed. Will work on updating scripts. Thanks!

Kyle Danicke | IT Senior Analyst Programmer | Enterprise API Management |
507-293-9503 | ***@***.******@***.***>
Mayo Clinic | 5777 E Mayo Blvd| Phoenix, AZ 85054 | www.mayoclinic.org<http://www.mayoclinic.org/>

From: keyrunner ***@***.***>
Sent: Friday, October 4, 2024 4:35 PM
To: launchiamenterprise/keyrunner ***@***.***>
Cc: DL MCCP Apigee Admins ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [launchiamenterprise/keyrunner] KeyRunner removing environment variables and then creating thousands of lines of blank variables. (Issue #60)


@Mayo-API-Management<https://github.com/Mayo-API-Management> just wanted to check in - is this still an issue?

-

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management We were able to reproduce the issue and fix it. The problem was related to an async operation. Since we encrypt the environment variables and the function itself isn't async, KeyRunner intercepted it differently. We're now testing thoroughly and plan to release a minor version in the next 1-2 days.
