### ISSUE TITLE
Collection deleted when selected and mouse dragged to left

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#61]
**Describe the bug**
In the Collection window, if you select the Collection, hold the mouse button down and drag to the left, the Collection is deleted.

**To Reproduce**
1. Go to the Collection window
2. Select a Collection
3. As the Collection is selected, hold down the left mouse button
4. Drag to the left
5. The Collection is deleted.

**Expected behavior**
At least a warning popup should be displayed, if this behavior is correct.

**Screenshots**
![image](https://github.com/user-attachments/assets/fdae9ce3-de4c-458c-983c-0aec019952d9)
![image](https://github.com/user-attachments/assets/c1f34890-a079-4d86-a627-6f66f40953e6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Additional context**
Is there a way to recover the deleted collection?  This is not a behavior that I am expecting.  If the Collection was moved somewhere instead, where is it.  I have had to recreate work because this happened inadvertently.

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management we just tried this scenario, the collection is not actually deleted. 

when a collection is dragged out of the collection window, it doesn’t get deleted but may be moved into another collection as a subfolder if the mouse is released within the window. We're working on a fix that will add a popup to confirm the destination folder ensuring the collection is only moved once confirmed. This update will be included in the next minor version.

For now, please search in other collections, and you should be able to find the collection you think was deleted.

While trying this, we also found a minor issue where the search function doesn’t include subcollections. We're fixing that as well. In the meantime, you can manually expand collections to search for it.

Please let us know if you were able to locate the collection!

**Comment by launchiamenterprise** [comment]
@Mayo-API-Management This is fixed now. Please update to latest (V#1.0.67). 
Fix : You will get a confirmation popup when moving collections around.
