### ISSUE TITLE
UI/UX:  The 2 main centered select boxes (drop-down) in the top nav are missing labels

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#65]
**Is your feature request related to a problem? Please describe.**
First of all, nothing mentioned down below is critical, let's be clear, it's all purely UI/UX enhancements/suggestions/cosmetics.
Just trying to help by sharing my own experience using the tool for the first time, where I found it confusing and so where imo it leaves some more room for improvements, that's all. Very promising product otherwise, thanks for that.

**Describe the solution you'd like**
I'm currently exploring the free version (after migrating away from postman), so I'm not sure if it's because I'm using such version, but I can't seem to do anything with the first main drop-down having a default hardcoded value of "Default".

The default value "Default" doesn't really bug me by its name, what bugs me are the following UI/UX items:

1.  the 2 drop-downs do not have labels, so it's hard to know what they are what they do. I have the feeling that the first one is maybe the "project" or perhaps the "workspace", and maybe those features are only available to the paying/Enterprise edition? If answer is yes, then if that option is irrelevant to free users exploring or using the tool, then perhaps we could hide the first drop-down on the free edition if totally unusable; if you would rather keep it displayed, then would be nice to at least add a small label on top of each drop-down telling what they are, that's a very basic UX rule, plus adding some note when that first drop-down is expended/opened to tell the user if it's irrelevant with his/her current [free] version..  I actually lost time trying to play with it, or navigate in various menus, and even went online trying to read keyrunner online doc to find more about its usage, but couldn't find anything.
![Screenshot 2024-10-09 at 4 31 26 PM](https://github.com/user-attachments/assets/d70198da-7855-404c-9319-597099297308)

2. the 2nd drop-down is a tiny more obvious, since when you open it, it says inside it "Select Environment", so at least you can discover that way what it controls, but still, just like previous point, I would suggest adding a small label on top of the drop-down for clarity.
![Screenshot 2024-10-09 at 5 00 24 PM](https://github.com/user-attachments/assets/4e331f8f-fbfd-4219-b1a1-f2cd25432d26)

3. the "New" button next to the env select box is also confusing, UX wise, since it doesn't tell what it can create from it's name, and normally when you see such pattern in a tool, you can assume that it's because it can create something that is contextual, e.g. something near the button, and in this case, what is near is the environment selector/drop-down right on its left, so you would guess the new button can help you create a new environment, but actually not, it allows to create an "http request", "websocket" or "socket.io".......so perhaps renaming the button something like "New Request" would be more clear.. And back to the environment creation topic, well, it's odd that you have to go as far as the left nav and select Environment to get a new env created, when there is an actual env selector on the main nav screen to the top; the suggestion here is it would be nice if either creating a new environment shortcut button could be added to the "New" dialog, unless it gets renamed to "New Request" like suggested above, then let's not mix topics, and then hide the "Create new environment" shortcut button/link inside the env selector/drop-down, as the very last option, would imo clearly improve navigation and clarity around the overall environment usage, when combined with previous point 2 above.
![Screenshot 2024-10-09 at 5 00 35 PM](https://github.com/user-attachments/assets/b1a76b91-0c67-48a6-ad66-e92382cbbf7e)

**Comment by launchiamenterprise** [comment]
@frank-duq By the way, 'Default' refers to the local workspace( all collections and requests are stored locally on your machine). Soon, we will add the capability to create multiple local workspaces, a feature currently available only to enterprise customers. May be for now we will add a tooltip to make it clear.

**Comment by launchiamenterprise** [comment]
@frank-duq  This has been addressed  with our latest release (V#1.0.69), Please update to latest version. Also, please let us know if you would like to see any more improvements.

**Comment by frank-duq** [comment]
Yes, much clearer now, nice work!
