### ISSUE TITLE
[Alter Behavior] Activity panel & primary side bar

### ISSUE THREAD

**Issue by Sharaf5** [launchiamenterprise/keyrunner#7]
![Screenshot_20240305_220510](https://github.com/launchiamenterprise/keyrunner/assets/36330265/35ae6031-56cd-42ab-9a0d-267d66b19ab3)

As you see in the screen above
you do have an icon for your application but the side bar only opens keyrunner panel

Alternatively you may :
- [x] ignore the side bar and switch the funcion of button inside it to the activity bar icon like what many project dashboards do ( one on github : https://github.com/bobmagicii/vscode-dashboard )
- [ ] swich to a mode ( like : Full screen  and zen mode if possibe ) that only focus on keyrunner if possible
- [ ] Add the key runner icon to the top shortcuts besides tabs ( where the mouse is pointing )

> I think any of them would be better behavior for such extention

**Comment by launchiamenterprise** [comment]
@Sharaf5 this has been addressed with v1.0.60 . Please update to current version.

**Comment by launchiamenterprise** [comment]
@Sharaf5 this has been addressed with v1.0.60 . Please update to current version.

**Comment by Sharaf5** [comment]
nice work
it need some enhancements as it appear then disappear but it's better than before
