### ISSUE TITLE
Request Pre-script js execution errors are empty in the Keyrunner Console (e.g. not providing what's the js error & line number)

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#71]
**Describe the bug**
When running a request containing some pre-script js code (the same applies to post-script code btw), when you've got an error with your js code and the pre-script execution fails on it, the keyrunner console will tell you that the pre-script contains an error and crashed, but currently even though you can expend that console error, it doesn't contain anything, it's simply an empty node. 

This makes it quite cumbersome to debug and find the error, when your js script is becoming slightly bigger, like it is the case for me, I'm generating lots of "random" faker data to be injected in the request body, so several js functions as well etc, but when I have an error with my pre-script code, it's pretty hard to find where, I have to add several console debug logging to find where the error is, which could be avoided if current expected behavior would be in place. Cheers

**To Reproduce**
1. Create a new request
2. Add some pre-script js code into it, and introduce a js code error somewhere (e.g. try to access an undefined variable)
3. Open the keyrunner console
4. Execute the request
5. look into the keyrunner console for the "pre-script error", and try to expect it.
6. you'll see no details is given as to what the error is, and what line generated it.

**Expected behavior**
The pre-script console error should contain the exact error returned by the js sandbox runtime, including the line number in your pre-script where your js code currently contains an error that made the js runtime to crash.

**Screenshots**
![Screenshot 2024-10-11 at 1 04 19 PM](https://github.com/user-attachments/assets/c5e4048a-0ee7-4f8f-8956-89f4bd20d1ac)

![Screenshot 2024-10-15 at 11 48 48 AM](https://github.com/user-attachments/assets/5af5fc4c-fac6-47c0-9fd2-5234007d8435)

**Desktop (please complete the following information):**
 - OS: macos
 - Version: 1.0.67

**Comment by launchiamenterprise** [comment]
@frank-duq Thanks for the detailed explanation. We’ll address this issue soon and update this thread with release date.

**Comment by launchiamenterprise** [comment]
@frank-duq  This has been addressed  with our latest release (V#1.0.69), Please update to latest version.
