### ISSUE TITLE
Feat:  would be nice to be able to [re] import exported environment values/json

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#75]
**Is your feature request related to a problem? Please describe.**
Not a problem per say, it's just that today, it is already possible to "export" a given keyrunner environment into a json file.

**Describe the solution you'd like**
It would be quite nice to be able to [re] import such exported keyrunner environment json file, so that the export file can 1) act as a backup, and 2) be shared with others if needs be.

**Describe alternatives you've considered**
n.a.

**Additional context**
![Screenshot 2024-10-15 at 3 20 38 PM](https://github.com/user-attachments/assets/180a401d-ae88-40be-aa36-0da08fd3d367)

**Comment by launchiamenterprise** [comment]
@frank-duq this feature is already available .We will add a menu item as well for better UX  

![image](https://github.com/user-attachments/assets/8b27ec4b-d599-4302-a065-b25bfb6e34a8)

**Comment by frank-duq** [comment]
Ohhh I see, nice!

My bad, I was looking directly into the Environment section, so yeah, I guess it wouldn't hurt to repeat that link inside the Env section as well perhaps, as a ux enhancement, but it's great the functionality already exists!
![Screenshot 2024-10-15 at 7 15 51 PM](https://github.com/user-attachments/assets/8c4ab90b-393c-4878-bb40-ed4635623dfb)

**Comment by launchiamenterprise** [comment]
Closing this issue , Import functionality will be moved to top bar globally for better UX.
