### ISSUE TITLE
[Feature request] Add support for more HTTP methods

### ISSUE THREAD

**Issue by Sharaf5** [launchiamenterprise/keyrunner#8]
As new HTTP methods arrive you may support them regurarly like PROPFIND
I suggest it may be useful in some scenarios
![Screenshot_20240305_223849](https://github.com/launchiamenterprise/keyrunner/assets/36330265/c96323ec-4990-4afe-943d-f88e9a6f833a)

You may also support custom methods

**Comment by launchiamenterprise** [comment]
@Sharaf5 Support for more HTTP methods has been added. Please update to the latest version v1.0.56 and let us know if you have any further requests or encounter any issues.

**Comment by Sharaf5** [comment]
I could confirm it's working here on the stable vscode version after restarting vscode
Thanks a lot
