### ISSUE TITLE
Q: what's the best way to find out if a new version has been released, and what are its release notes?

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#85]
Hi, 
so as the title says, I was simply wondering if there was any online location made available to us, to find out:

1. ...when a new release/version of KeyRunner has been published / what's the latest current available version published?
2. ...what's the release notes of any given released/published version?

For now, all I could find was this link:
https://github.com/launchiamenterprise/keyrunner/releases

..but it doesn't seem to be updated systematically as new versions are being released, its missing several versions, and it is currently not up-to-date (at time of writing, the last documented release notes are for version `1.0.64`, even though the current latest keyrunner version available for download is `1.0.67`, which doesn't seem to be documented..):
![Screenshot 2024-10-17 at 1 14 26 PM](https://github.com/user-attachments/assets/0acb9a5d-dc7f-40e0-9367-c75eecf0594f)

![Screenshot 2024-10-17 at 1 14 51 PM](https://github.com/user-attachments/assets/7d12a487-1392-4cd4-b1a5-986d0d3d58c0)

The only way I've found to know if a new version is actually available (but without any release notes associated to it), is to actually go to the [project's home page](https://keyrunner.app/), and mouse over the [Windows or Mac OS] download links, and check at the bottom of my browser the associated link's URL, and from that download URL / filename, identify what's the current latest version which is part of that filename, it does work, but that's not super convenient:
![Screenshot 2024-10-17 at 1 10 04 PM](https://github.com/user-attachments/assets/ead88444-2ad0-424a-a7ef-34a8a6150f69)

I understand obviously if you've been working hard on opened tickets lately (and you are quite responsive actually), and perhaps you had to cut some corners elsewhere like producing such release notes documentation etc to compensate, but I was just wondering if there's actually an existing location that I'm perhaps unaware, which provides all this information already (latest available version + versions' release notes).

---

_**Suggestions / food for thoughts:**_

**1-** Add a new label on the project home page's top nav bar, which displays current latest available version.

**2-** Maintain the [release notes](https://github.com/launchiamenterprise/keyrunner/releases) for every single new future version being released (if at all possible, I understand this is on best effort, just a friendly suggestion, you're the boss!..)

**3-** Eventually, consume the above [maintained] release notes' github file and make it available on the website as a new page somewhere, or perhaps just add a simple release notes link in the website somewhere that send you to that github page, to make it easy for users to find out new releases' info, and it's always a great way to showcase that the project is still very well alive and getting updated periodically (and professionally).

thanks!

**Comment by launchiamenterprise** [comment]
@frank-duq We have built a CI/CD pipeline that will automatically update the release notes every time a new version is released. Starting with the next release, this process will be fully automated . Also, we are planning to add a dedicated page on our website where users can view all updates related to new releases.

**Comment by launchiamenterprise** [comment]
@frank-duq Starting now, all release notes and updates will be available at our dedicated changelog page: https://keyrunner.app/changelog. Please refer to this link for all future updates and improvements!

**Comment by frank-duq** [comment]
Will this link be linked somewhere on your website eventually?

**Comment by launchiamenterprise** [comment]
yes, there is a caching issue that's preventing the updated content from loading. We will fix that soon. 

 The current content is being read from: : https://github.com/launchiamenterprise/keyrunner/blob/main/ReleaseNotes.md
