### ISSUE TITLE
The "History" feature (from the left nav) does not seem to work

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#86]
**Describe the bug**
After executing a few requests, the History panel remains empty, not showing any executed requests, and instead, telling you:
>"Your request history is currently empty
As you make API requests, they'll be stored here for easy reference and re-execution. Start making requests to populate your history!"

**To Reproduce**
1. Create and Submit a Request
2. Click on the "History" tab from the left nav bar
3. See that the History panel remains empty, not showing your expected executed request.

**Expected behavior**
All executed requests are displayed in the History panel as expected (with the possibility to 'clear' them through some button..)

**Screenshots**
![Screenshot 2024-10-18 at 11 57 02 AM](https://github.com/user-attachments/assets/a8f0f6dd-54f4-4580-b681-6fb2ec7b1442)

**Desktop (please complete the following information):**
 - OS: macos
 - Version 1.0.67

**Comment by launchiamenterprise** [comment]
@frank-duq Have you tried switching the workspace after submitting the request? We tested this across multiple workspaces and could see the history without any issues.

Could you please check in this folder (C:\Users\{{user}}\AppData\Roaming\Code\User\globalStorage\keyrunner-lite-by-liam) and confirm if there is a file named "previous_requests"?

<img width="484" alt="image" src="https://github.com/user-attachments/assets/fcd9677c-a182-4086-9f89-1e2d98dbab90">

**Comment by frank-duq** [comment]
The "previous_requests.json" is indeed empty:
(I'm on macos btw)


![Screenshot 2024-10-18 at 1 02 29 PM](https://github.com/user-attachments/assets/35699af3-6a20-40e9-ac4e-acf63ca2c4f4)

**Comment by launchiamenterprise** [comment]
@frank-duq Please update to v1.0.70. This issue should be fixed now. Let us know if the issue still persists.

**Comment by frank-duq** [comment]
Confirmed, it's working now!

The only thing I would add to it, is the ability to CLEAR any folder in there, but yeah, that's a feature request, current issue can be closed, tx.

**Comment by launchiamenterprise** [comment]
Thanks for raising the issue. This was an edge case that we missed and not sure how this scenario came up:) . Clearing folders and a trash screen for retrieval of any deleted requests/collections/history is in our pipeline. We will keep you posted.
