### ISSUE TITLE
Feat(ux):  store Collections' opened folders state (e.g. avoid resetting the opened folders state when navigating away and coming back)

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#87]
**Is your feature request related to a problem? Please describe.**
When opening one or more collection folders and/or sub-folders, as you are currently working in some of those, sometimes you want to go check something else located somewhere else in the app, like another tab from the left nav, but then, when coming back to the Collections tab, all your opened folders have been reset and are all collapsed, which is annoying since you need to re-open them all again every time.

**Describe the solution you'd like**
Save/persist the state of the collections' opened folders, so that when navigating away from the "Collections" tab, for instance when viewing your Environment env vars, and then coming back to your "Collections" tab, all your 'currently under work' collections' folders/sub-folders remain opened.

Bonus point in adding some button to collapse all opened collections' folders and sub-folders, but this is much less needed than what is described above.

**Describe alternatives you've considered**
Well, as mentioned, currently the alternative is to always have to re-open your collections folders/sub-folders manually, which is just annoying when clicking around and using the tool extensively, but at least this is not a show-stopper, but definitely a great to have in terms of overall UX.

**Additional context**
![Screenshot 2024-10-18 at 11 47 13 AM](https://github.com/user-attachments/assets/fd158eed-4689-4c43-adc6-c9d42ab4690e)

**Comment by launchiamenterprise** [comment]
@frank-duq this has been addressed in V#1.0.69 , please update to latest.

**Comment by frank-duq** [comment]
Confirmed, it's working, very niice, thanks!
