### ISSUE TITLE
Odd error in the console after executing a simple request with latest version 1.0.69

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#88]
**Describe the bug**
Odd console error displayed when running a simple request, with latest `1.0.69`.

**To Reproduce**
1. Open the Console
2. Execute a request
4. See error in console

**Expected behavior**
No such error seen in the Console.

**Screenshots**
![Screenshot 2024-10-21 at 11 55 09 AM](https://github.com/user-attachments/assets/60fdcda5-3de8-470b-836b-13f3007344d8)

**Desktop (please complete the following information):**
 - OS: macos (silicon)
 - Version: `1.0.69`

**Comment by launchiamenterprise** [comment]
@frank-duq Please update to v1.0.70. This issue should be fixed now. Let us know if the issue still persists.

**Comment by frank-duq** [comment]
Fixed, thanks!

**Comment by launchiamenterprise** [comment]
awesome! thanks for confirming
