### ISSUE TITLE
Running an entire collection ignores all defined requests' Pre and Post scripts  (+ the Playground boxes generated when running existing collections of 10-20+ requests are hard to understand [no visual sequence, no links & boxes overlaps] + the Playground Response panel is missing the Requests records + the Console is missing the Response details)

### ISSUE THREAD

**Issue by frank-duq** [launchiamenterprise/keyrunner#90]
**Describe the bug**
Ok, after test driving for 1-2 weeks the individual requests (with the Console etc, pre-script, post-script, env vars, etc), I've now reached the point of testing to run my entire collection with Keyrunner.

3 things that are happening to me right now as I'm starting testing the Collection Run feature of KeyRunner:

---

**1)**  The playground boxes that get generated to represent all my Collection APIs are forming a confusing rectangle, and it's really hard to determine by looking at it, what's the order of APIs to be called, by looking at all those boxes... (left to right, and then from top to bottom I suppose? but still, not super intuitive...).

As suggested in the screenshot below, I would simply organized all boxes on one single horizontal line by default, first request of the collection being the first one on the left, and the last api request from my collection would then be the last box to the far right, all on the same line, so it makes it easy to understand the order. Ideally, would be nice to see arrows from each box on the left to its next box to its right, to see the sequential order of execution...

---

**2)**  Issue number two is the real problem here. My very first collection api that runs is the one that obtains an authentication bearer token, and using post-script, it stores it as a keyrunner env var. Then, my second request does some http post, but doesn't need the auth token. Then, starting from the 3rd request, all subsequent requests will need the token that has been stored as an env var, so they all use the "inherit from parent" authentication, since I've configured in my top parent collection folder a bearer authentication, and pointing to the env var value (e.g.   key=BEARER, value={{my_auth_token}} ).

So my guess is that the "Collection Run" is not interpreting correctly the "inherit from parent" authentication for all those requests having such authentication configuration, but it should, since this would allow to run all collection requests both individually AND through a Collection Run. I obviously don't want to have to modify all my individual collection request authentication, and change the "inherit from parent' value for the BEARER auth mode, that would be painful to maintain etc.

--- 

**3)** Last error, which goes hand in hand with issue 2) above, is that currently, in the Console, such error does not display anything about the http response itself (no response code, no response headers, no response body, nothing..), only the error string that the request failed to send is showing, which is not helping investigating the problem, and also, I doubt that it's a "request" issue in this case, pretty sure I'm hitting the server, and it's just an auth issue.

---

**Screenshots**
![Screenshot 2024-10-24 at 5 34 45 PM](https://github.com/user-attachments/assets/e6314e6e-b2b1-4770-a264-dd53d0b97050)

**Desktop (please complete the following information):**
 - OS: macos (silicon)
 - Version: `1.0.70`

thanks

**Comment by launchiamenterprise** [comment]
@frank-duq We are still going through the details, just wanted to let you know you can click on the response tab and see the sequence of requests/responses along with the details (response code, body etc )

![image](https://github.com/user-attachments/assets/6c641a3b-1858-4a1b-b0c6-5e03b92b66d5)

**Comment by frank-duq** [comment]
Oh yes I see, ok, maybe I'll propose something later regarding that "Response" button:P, perhaps not the most intuitive, but the Response panel itself is quite nice!   Only missing...the "Requests" perhaps, which are currently in another location, e.g. in the Console, so things are sort of splitted, but fine, at least the data is there for now...

So, here's my Playground Response panel, it's actually saying that all my failing requests have a 500 error, and they all have that same problem, which I don't know where it could be coming from, especially since the first failing request is a simple GET request with a url param coming from keyrunner env var, but other than that, it does not contain anything in its body (e.g. empty request body), and the only other thing it has, is that "inherit from parent" authentication, like all the other failing ones...  But that error message coming from my server is strange, that "invalid character '{' " ...

![Screenshot 2024-10-24 at 6 28 08 PM](https://github.com/user-attachments/assets/5c968670-2a5f-4ff4-9f3a-5ff4afb8eabf)

**Comment by frank-duq** [comment]
Ok, after some more investigation, confirmed, the remote server is failing because it is unable to deserialize the auth bearer token, because the value that is actually sent wasn't replaced by KeyRunner, the env var placeholder "{{...}}" was kept as is, and sent to the server, reason why I'm getting all those "{" errors...!:)

And so, this pushed me to get back in KeyRunner, and check the request headers being sent, and I could easily confirm this:
![Screenshot 2024-10-24 at 6 57 40 PM](https://github.com/user-attachments/assets/2a1f1094-7b9b-4de0-9ada-1f05a3d0c27f)

---
Oh, as I continue the investigation as I'm writing this msg, actually, I think I may just have found the real problem:
After a Collection Run from the Playground, I'm opening the Console, and can't see any of the "Pre-Script" nor the "Post-Script" executions for my collection requests!  (I have many requests with pre-script and post-script, and the whole collection run fully depends on those scripts, or else nothing will work......same for.....the authentication!  my first request is the one getting the auth bearer token, and saving it as a keyrunner env var, so that all subsequent requests use it as already mentioned, so if the post-script is not executed, auth will definitely fail and the "{{....}}" won't get replaced by keyrunner, so that must be it, but I'll let you confirm! ; )

cheers

**Comment by launchiamenterprise** [comment]
@frank-duq we were able to reproduce this issue, scripting functionality was recently added and while running the collection scripts are not correctly invoked. We are working on a fix and expect to publish a new version over the weekend.

**Comment by launchiamenterprise** [comment]
@frank-duq this is being worked on now . Hopefully we will release a new version this week after testing. You should be able to run the collections without any issues. We are also changing the UI for understanding the sequence of run, playground will remain as a separate feature and collection run will have its own dedicated UI

**Comment by launchiamenterprise** [comment]
@frank-duq This is addressed in our latest release, Please update to V#1.0.71
