### ISSUE TITLE
cursor extension: KeyRunner is not set Cookie for HTTP response of 302 status

### ISSUE THREAD

**Issue by theshaodi** [launchiamenterprise/keyrunner#93]
**Screenshots**
this is KeyRunner's request config.
![SCR-20241030-lyw](https://github.com/user-attachments/assets/2cb388f4-8906-49fa-b637-804cc0ed4e74)

this is screenshot of KeyRunner's tcpdump.
![SCR-20241030-ldr](https://github.com/user-attachments/assets/3b7d9621-efd1-4875-8ae8-2b9acd0821fd)
![SCR-20241030-le1](https://github.com/user-attachments/assets/9a621cc8-9ab0-4655-a5f0-7e2835da2741)

and this is tcpdump's source file.  
[osn_redis.cap.zip](https://github.com/user-attachments/files/17567951/osn_redis.cap.zip)

**Desktop:**
 - OS: macOS
 - Version 10.15.7

**VScode extension :**
 - OS: macOS
 - Version v1.0.70

**Additional context**

**Comment by launchiamenterprise** [comment]
@theshaodi we are looking into and will provide an update soon

**Comment by launchiamenterprise** [comment]
@theshaodi Issue should now be fixed in desktop clients with the latest release, we are working on a fix for vscode

**Comment by theshaodi** [comment]
> @theshaodi Issue should now be fixed in desktop clients with the latest release, we are working on a fix for vscode

I'll try it out on KeyRunner's latest desktop client, the most secure API debugger I've used so far, and hopefully it'll be even better

**Comment by launchiamenterprise** [comment]
Thanks for the feedback! We’re always working to make it even better. If you have a moment, a review on VS Code would be appreciated!

https://marketplace.visualstudio.com/items?itemName=KeyRunner.keyrunner&ssr=false#review-details

**Comment by theshaodi** [comment]
It is performing optimally on the current version 1.0.71; Thank you for your support。
