### ISSUE TITLE
Local Host V1.0.71 Error

### ISSUE THREAD

**Issue by Mayo-API-Management** [launchiamenterprise/keyrunner#95]
**Describe the bug**
After the automatic update to 1.0.71 we all cannot hit our local host via SSL.  Get: 
{"message":"unable to verify the first certificate","name":"Error"}

The cert is in our Trusted CA list, which works for .net and worked prior to the ...71 update. 
The cert is an  Visual Studio generated, IIS development cert, not CA issued. 

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by launchiamenterprise** [comment]
we are looking into this and will provide an update shortly
